server:
    port: 8080
endpoints:
    shutdown:
        enabled: true
    restart:
        enabled: true


spring:
    application:
      name: pos-service
    datasource:
        url: jdbc:mysql://${POS_DATASOURCE_HOST:localhost}:${POS_DATASOURCE_PORT:3306}/${POS_DATASOURCE_DBNAME:pos_db}
        username: ${POS_DATASOURCE_USERNAME}
        password: ${POS_DATASOURCE_PASSWORD}
        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1
    # Spring Data JPA configuration
    jpa:
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate:
            # To be updated in real production usage! update create-drop none
            ddl-auto: none
            show-sql: false

#se habilita liquidbase
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.xml
# Comma-separated list of runtime labels to use.
spring.liquibase.labels: ${POS_LIQUIBASE_LABELS:}

